# Site settings
title: Hung Neox
url: "http://butchiso.com"
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Europe/Helsinki
description: >
  Professional keyboard masher and screen watcher | Web Developer.

# Your information
email: hungnq1989@gmail.com
author: Hung Neox
avatar: "//www.gravatar.com/avatar/4a44cc577eaca63e8eb110932f15bc0a?d=mm&s=135"
profile: Full stack developer.
twitter_username: hungneox
github_username:  hungneox

# Comment Service
#  choose one and un-comment the line to active it
disqus_shortname: butchiso

permalink: /:year/:month/:title.html
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 20
paginate_path: "page/:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
